name: grabbing streams

on:
  schedule:
    - cron: '0 */1 * * *'
  
  
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

       
      - name: config
        run: |
          git config --global user.email "<>"
          git config --global user.name "Update"
      
      
      - name: grab m3u files
        run: |
            pwd
            cd ./core/platforms/
<<<<<<< HEAD
            python3 twitch.py TESTv > ../../streams/TEST.m3u8
=======
            python3 twitch.py testtv > ../../streams/test.m3u8
>>>>>>> fa38480dc9328251fa6aeae47fa1b7e69192d292
      - name: git add
        run: |
          git add -A
          ls -la 
          
      - name: commit & push
        run: |
          git commit -m "streams updated"
          git push
            
            
            
            
            
            
            
      
            
            
            
            
            
            

